server:
  port: 8088
  tomcat:
    basedir: ./
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D %{User-Agent}i'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.111.2.107:3306/qinggua?serverTimezone=GMT%2B8&useUnicode=true&amp&characterEncoding=utf-8
    username: root
    password: 990304

  # timezone of jackson(when get time from database)
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # the file size
  servlet:
    multipart:
      # the max size of one file
      max-file-size: 100MB
      # once request the max size of file
      max-request-size: 101MB
# log for mysql
logging:
  level:
    com:
      yznu:
        qinggua: debug

#mybatis-plus:
#  mapper-locations: classpath:mapper.admin/*.xml